table olist_products_dataset
	lineageTag: b616ffb2-f37e-48d4-a08c-c2c5fcf27820

	column product_id
		dataType: string
		lineageTag: 253e4614-9953-40c0-aae8-2e92ffaac090
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: 3863c913-8f6c-45be-9d1f-ee18bd918f7b
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: int64
		formatString: 0
		lineageTag: 73c593a5-6480-4d1d-b41b-95e2dc514806
		summarizeBy: sum
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: int64
		formatString: 0
		lineageTag: 15bfd5fe-29eb-4bd7-a69b-498a35c515f7
		summarizeBy: sum
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: int64
		formatString: 0
		lineageTag: 3a7bd955-2b9d-4f67-9c44-3f952125f8d1
		summarizeBy: sum
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: d9c9e6e8-b423-4143-aff1-d28fa9805536
		summarizeBy: sum
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 33697774-8984-48e4-ae5e-2c9a2a8bbf1b
		summarizeBy: sum
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: 326fe6a6-7202-47cf-bf6b-20fe1d8722bd
		summarizeBy: sum
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: f6b80ddb-bac6-4ec1-a093-8f92b339b4cf
		summarizeBy: sum
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	partition olist_products_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\nestasia\data\raw\olist_products_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_category_name", type text}, {"product_name_lenght", Int64.Type}, {"product_description_lenght", Int64.Type}, {"product_photos_qty", Int64.Type}, {"product_weight_g", Int64.Type}, {"product_length_cm", Int64.Type}, {"product_height_cm", Int64.Type}, {"product_width_cm", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

